Use safe accessor on forum roles pages
This was raising a `NoMethodError: undefined method '[]' for nil` error
causing `/manage/special_forum_roles` and `/manage/unit_forum_roles` to
fail. Likely because we removed the vanilla integration in November but
still have some vanilla forum role records in the database.